#!/bin/sh

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

$DIALOG --inputbox "Please Enter Continent/City:" 8 35 2>/tmp/input.$$

time=$(export TZ=`cat /tmp/input.$$`;date)
cty=`cat /tmp/input.$$`

MSG="Current Local Time in $cty is:  \n\n$time"

$DIALOG --yesno "$MSG" 7 20 || end
	
