#!/bin/sh
zenity --entry --entry-text="type" --text "Please Enter Continent:" > /tmp/tmp1
zenity --entry --entry-text="type" --text "Please Enter City" > /tmp/tmp2


input=`cat /tmp/tmp1 /tmp/tmp2`

stringarray=($input)

export TZ="${stringarray[0]}"/"${stringarray[1]}"
zenity --info --text "Current Date and Time:\n`date`"
