#!/bin/sh

TIME=TimeTxt
HOST=localhost
PORT=1234

GETTEXT="gettext -d Main"

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

$DIALOG --inputbox "Please Enter Continent/City:" 8 35 2>/tmp/city.$$

curr_time=$(export TZ=`cat /tmp/city.$$`;date)
cty=`cat /tmp/city.$$`

MSG="Current Local Time in $cty is:  \n\n$curr_time"

$DIALOG --yesno "$MSG" 7 20 || end
