#!/bin/sh

TIME=TimeTxt
HOST=localhost
PORT=1234

GETTEXT="gettext -d Main"

#!/bin/sh
zenity --entry --entry-text="type" --text "Please Enter Continent:" > /tmp/tmp1
zenity --entry --entry-text="type" --text "Please Enter City:" > /tmp/tmp2


input=`cat /tmp/tmp1 /tmp/tmp2`
input1=`cat /tmp/tmp2`
stringarray=($input)

export TZ="${stringarray[0]}"/"${stringarray[1]}"
zenity --info --text "Current Date and Time in $input1:\n`date`"
