#!/bin/bash

FILE1=/tmp/tzone-$$

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

end () {
        rm -f $FILE1
        exit
        }
while true
do
$DIALOG --title " Timezone" --clear \
\
        --inputbox "Please put your desired Continent/Country Name: " 25 59 4>$FILE1 || end
        
        ab=$(export TZ=`cat $FILE1.$$`;date)
        
        MSG="Now the time is: $ab \n\nContinue?"
        
        $DIALOG --yesno "$MSG" 7 20 || end
        
done
