#!/bin/bash

echo `gettext -d timecl "Application stared. Press Ctrl+c to exit."`
 while [ True ]
 do
 	echo `gettext -d timecl "Enter the zone:"`
 	read Z
 	echo `gettext -d timecl "Enter the city:"`
 	read C
 	/tmp/input.$$="$Z/$C"
 	
 	time=$(export TZ=`cat /tmp/input.$$`;date)
cty=`cat /tmp/input.$$`

 	
 	MSG="Local Time in $cty is:  \n\n$time"

$DIALOG --yesno "$MSG" 7 20 || end
 	
done
